config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'maps#index'  

  namespace :api do
    namespace :maps do 
      resources :searche_year, only: :index, defaults: { format: :json }
      resources :searche_word, only: :index, defaults: { format: :json }
    end
  end
  get "about", to: "about#index", as: "about"
  get 'tos', to: 'about#tos', as: 'tos'
  resources :maps, only: [:index]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/history.rb
# frozen_string_literal: true

class History < ApplicationRecord
  validates :label, presence: true
  validates :abstract, presence: true
  validates :latitude, presence: true, numericality: true
  validates :longitude, presence: true, numericality: true
  validates :accrual_date, presence: true
end

app/controllers/about_controller.rb
# frozen_string_literal: true

class AboutController < ApplicationController
  def index; end

  def tos; end
end

app/controllers/api/base_controller.rb
# frozen_string_literal: true

class API::BaseController < ApplicationController
end

app/controllers/api/maps/searche_word_controller.rb
# frozen_string_literal: true

class API::Maps::SearcheWordController < API::BaseController
  def index
    @search_rusults = History.where('label LIKE?', "%#{params[:keyword]}%").or(History.where('abstract LIKE?', "%#{params[:keyword]}%"))
    respond_to do |format|
      format.html { redirect_to :root }
      format.json { render json: @search_rusults }
    end
  end
end

app/controllers/api/maps/searche_year_controller.rb
# frozen_string_literal: true

class API::Maps::SearcheYearController < API::BaseController
  def index
    searche_year = params[:year].to_i
    @all_history_position = History.where(accrual_date: "#{searche_year}-01-01"..."#{searche_year + 100}-12-31")
    respond_to do |format|
      format.json { render json: @all_history_position }
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/maps_controller.rb
# frozen_string_literal: true

class MapsController < ApplicationController
  def index; end
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/maps_helper.rb
# frozen_string_literal: true

module MapsHelper
  def map_page?
    params[:action] == 'index' && params[:controller] == 'maps'
  end
end

app/helpers/meta_tags_helper.rb
# frozen_string_literal: true

module MetaTagsHelper
  # rubocop:disable Metrics/MethodLength
  def default_meta_tags
    {
      site: 'Mapnica',
      reverse: true,
      charset: 'utf-8',
      description: 'Mapnicaは歴史の出来事を地図上に表示するサービスです',
      viewport: 'width=device-width, initial-scale=1.0',
      keywords: '歴史, 地図, history, map',
      og: {
        title: :full_title,
        type: 'website',
        site_name: 'Mapnica',
        description: :description,
        image: 'https://www.mapnica.net/ogp/ogp.png',
        url: 'https://www.mapnica.net'
      },
      twitter: {
        card: 'summary_large_image',
        site: '@Masamune_catcat',
        description: :description,
        image: 'https://www.mapnica.net/ogp/ogp.png',
        domain: 'https://www.mapnica.net'
      }
    }
  end
  # rubocop:enable Metrics/MethodLength
end

app/views/about/index.html.slim
- title 'About'
.main-container
  .static-text
    h3
      | 目次
    ul.about_list
      li
        a href="#about_mapnica"
          | Mapnicaとは
      li
        a href="#about_use"
          | 使い方
        ul.about_use
          li
            a href="#about_marker"
              | 歴史上の出来事を地図上にマーカーとして表示
          li
            a href="#about_year"
              | 年代による検索
          li
            a href="#about_keyword"
              | キーワード検索
    h3#about_mapnica
      | Mapnicaとは
    p.about-text-contents
      | Mapnicaは歴史の出来事を地図上に表示するサービスです。
      br
      | 年代やキーワードでの検索が可能で、検索した出来事が地図上に表示されます。
    h3#about_use
      | 使い方
      h4#about_marker
        | 歴史上の出来事を地図上にマーカーとして表示
      ul
        li
          | 歴史上の出来事を地図上にマーカーとして表示します。
        li
          | 表示されたマーカーをクリックすると、クリックされたマーカーの解説が表示されます。
      = image_tag('marker', alt: 'how to use marker', class: 'marker')
      h4#about_year
        | 年代による検索
      ul
        li
          | スライダーを操作することで年代による検索を実行し、検索結果のマーカーが地図上に表示されます。
      = image_tag('slider', alt: 'how to use slider', class: 'marker')
      h4#about_keyword
        | キーワード検索
      ul
        li
          | 入力したキーワードに合致した検索結果をリスト形式で表示します。
        li
          | 表示された検索結果をクリックすると、クリックされた検索結果の解説とマーカー、同じ年代の出来事が地図上に表示されます。
      = image_tag('keyword', alt: 'how to search by keyword ', class: 'marker')
    p
      = link_to 'Mapへ戻る', root_path, class: 'about-logo-button'

app/views/about/tos.html.slim
- title '利用規約'
.main-container.static
  .static-text
    h1
      | 利用規約
    p
      | この利用規約（以下，「本規約」といいます。）は，このウェブサイト上で提供するサービス（以下，「本サービス」といいます。）の利用条件を定めるものです。ユーザーの皆さま（以下，「ユーザー」といいます。）には，本規約に従って，本サービスをご利用いただきます。
    h2
      | 第1条（適用）
    ol
      li
        | 本規約は，ユーザーの本サービスの利用に関わる一切の関係に適用されるものとします。
      li
        | 本サービスは本サービスに関し，本規約のほか，ご利用にあたってのルール等，各種の定め（以下，「個別規定」といいます。）をすることがあります。これら個別規定はその名称のいかんに関わらず，本規約の一部を構成するものとします。
      li
        | 本規約の規定が前条の個別規定の規定と矛盾する場合には，個別規定において特段の定めなき限り，個別規定の規定が優先されるものとします。
    h2
      | 第2条（禁止事項）
    p
      | ユーザーは，本サービスの利用にあたり，以下の行為をしてはなりません。
    ol
      li
        | 法令または公序良俗に違反する行為
      li
        | 犯罪行為に関連する行為
      li
        | 本サービスの内容等，本サービスに含まれる著作権，商標権ほか知的財産権を侵害する行為
      li
        | 本サービス，ほかのユーザー，またはその他第三者のサーバーまたはネットワークの機能を破壊したり，妨害したりする行為
      li
        | 本サービスによって得られた情報を商業的に利用する行為
      li
        | 本サービスのサービスの運営を妨害するおそれのある行為
      li
        | 不正アクセスをし，またはこれを試みる行為
      li
        | 他のユーザーに関する個人情報等を収集または蓄積する行為
      li
        | 不正な目的を持って本サービスを利用する行為
      li
        | 本サービスの他のユーザーまたはその他の第三者に不利益，損害，不快感を与える行為
      li
        | 他のユーザーに成りすます行為
      li
        | 本サービスが許諾しない本サービス上での宣伝，広告，勧誘，または営業行為
      li
        | 面識のない異性との出会いを目的とした行為
      li
        | 本サービスのサービスに関連して，反社会的勢力に対して直接または間接に利益を供与する行為
      li
        | その他，本サービスが不適切と判断する行為
    h2
      | 第3条（本サービスの提供の停止等）
    ol
      li
        | 本サービスは，以下のいずれかの事由があると判断した場合，ユーザーに事前に通知することなく本サービスの全部または一部の提供を停止または中断することができるものとします。
        ol
          li
            | 本サービスにかかるコンピュータシステムの保守点検または更新を行う場合
          li
            | 地震，落雷，火災，停電または天災などの不可抗力により，本サービスの提供が困難となった場合
          li
            | コンピュータまたは通信回線等が事故により停止した場合
          li
            | その他，本サービスが本サービスの提供が困難と判断した場合
      li
        | 本サービスは，本サービスの提供の停止または中断により，ユーザーまたは第三者が被ったいかなる不利益または損害についても，一切の責任を負わないものとします。
    h2
      | 第4条（保証の否認および免責事項）
    ol
      li
        | 本サービスは，本サービスに事実上または法律上の瑕疵（安全性，信頼性，正確性，完全性，有効性，特定の目的への適合性，セキュリティなどに関する欠陥，エラーやバグ，権利侵害などを含みます。）がないことを明示的にも黙示的にも保証しておりません。
      li
        | 本サービスは，本サービスに起因してユーザーに生じたあらゆる損害について一切の責任を負いません。ただし，本サービスに関する本サービスとユーザーとの間の契約（本規約を含みます。）が消費者契約法に定める消費者契約となる場合，この免責規定は適用されません。
      li
        | 前項ただし書に定める場合であっても，本サービスは，本サービスの過失（重過失を除きます。）による債務不履行または不法行為によりユーザーに生じた損害のうち特別な事情から生じた損害（本サービスまたはユーザーが損害発生につき予見し，または予見し得た場合を含みます。）について一切の責任を負いません。また，本サービスの過失（重過失を除きます。）による債務不履行または不法行為によりユーザーに生じた損害の賠償は，ユーザーから当該損害が発生した月に受領した利用料の額を上限とします。
      li
        | 本サービスは，本サービスに関して，ユーザーと他のユーザーまたは第三者との間において生じた取引，連絡または紛争等について一切責任を負いません。
    h2
      | 第5条（サービス内容の変更等）
    p
      | 本サービスは，ユーザーに通知することなく，本サービスの内容を変更しまたは本サービスの提供を中止することができるものとし，これによってユーザーに生じた損害について一切の責任を負いません。
    h2
      | 第6条（利用規約の変更）
    p
      | 本サービスは，必要と判断した場合には，ユーザーに通知することなくいつでも本規約を変更することができるものとします。なお，本規約の変更後，本サービスの利用を開始した場合には，当該ユーザーは変更後の規約に同意したものとみなします。
    h2
      | 第7条（権利義務の譲渡の禁止）
    p
      | ユーザーは，本サービスの書面による事前の承諾なく，利用契約上の地位または本規約に基づく権利もしくは義務を第三者に譲渡し，または担保に供することはできません。
    h2
      | 第8条（準拠法・裁判管轄）
    ol
      li
        | 本規約の解釈にあたっては，日本法を準拠法とします。
      li
        | 本サービスに関して紛争が生じた場合には，本サービスの本店所在地を管轄する裁判所を専属的合意管轄とします。
    p
      | 以上

app/views/layouts/_footer.html.slim
footer.footer
  = link_to root_path, class: 'title' do
    = image_tag('logo', alt: 'Mapnica', class: 'footer__logo')
  .footer-icons
    .footer-icons__item
      a[href='https://github.com/masamune17/history_map' target='_blank' rel='noopener']

  img.icon[src='/icons/github.png']
  .footer-icons__item
    a[href='https://twitter.com/Masamune_catcat' target='_blank' rel='noopener']

  img.icon[src='/icons/twitter.png']
  .fotter-text
    small.footer__copyright
      | ©2021 masamune17

app/views/layouts/_header.html.slim
header
  .header__start
    label.header-menu.is-menu[for='menu']
      span.header-menu__bars
        span.header-menu__bar
      span.header-menu__label
        | Menu
    .title-container
      = link_to root_path, class: 'title' do
        = image_tag('logo', alt: 'Mapnica', class: 'logo')
  - if map_page?
    = render '/maps/slider_items_container'
  .header__end
    - if map_page?
      = render '/maps/search_container'
= render '/layouts/menu'

app/views/layouts/_menu.html.slim
input#menu[type='checkbox']
nav.menu
  label.close-explain-button[for='menu']
    span.batsu
  ul.menu__inner

  li.menu__item
    = link_to 'Map', root_path, class: 'menu__link'
  li.menu__item
    = link_to 'Mapnicaについて', about_path, class: 'menu__link'
  li.menu__item
    = link_to '利用規約', tos_path, class: 'menu__link'

app/views/layouts/application.html.slim
doctype html
html
  head
    = display_meta_tags(default_meta_tags)
    = csrf_meta_tags
    = csp_meta_tag
    script src='https://maps.googleapis.com/maps/api/js?key=#{Rails.application.credentials.maps[:google_maps_api_key]}', async: 'async', defer: 'defer'
    = favicon_link_tag '/favicon.ico'
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks': 'reload'
  body
    .wrapper
      = render '/layouts/header'
      = yield
      = render '/layouts/footer'
  = javascript_pack_tag 'application'

app/views/maps/_main_explain_item_container.html.slim
#main-explain-item-container.main-explain-item-container
  #close-explain-button.close-explain-button
    span.batsu
  .main-explain-items
    .accrual-date-container
      p.explain-text
        | 発生日
      p#accrual_date
    .label-container
      p.explain-text
        | 名称
      p#label
    .abstract-container
      p.explain-text
        | 概要
      .abstract-body
        .abstract-body__inner
          p#abstract

app/views/maps/_search_container.html.slim
.search-container
  label#search-btn.header-menu[for='search-btn-check']
    span.magnifying-glass
    span.header-menu__label
      | Search
  #js-search-items-container.js-search-items-container

app/views/maps/_slider_items_container.html.slim
.slider-items-container
  #js-slider-container.js-slider-container

app/views/maps/index.html.slim
.main-container
  = render 'main_explain_item_container'
  .map-container
    #map